### ISSUE TITLE
GitHub Actionsへの移行

### ISSUE THREAD

**Issue by Ryo-cool** [Ryo-cool/Nature-Spots#47]
# CircleCI から GitHub Actions への移行

## 現状の問題点

- CircleCI の設定が古い可能性
- GitHub Actions の新機能を活用できていない
- ワークフローの最適化が必要

#### フロントエンド用ワークフロー

```yaml
name: Frontend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'front/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'front/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint check
        run: yarn lint

      - name: Type check
        run: yarn tsc --noEmit

      - name: Run tests
        run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Build application
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: dist/
```

#### バックエンド用ワークフロー

```yaml
name: Backend CI/CD

on:
  push:
    branches: [main, develop]
    paths:
      - 'back/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'back/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Database setup
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: bundle exec rspec

      - name: Run rubocop
        run: bundle exec rubocop
```

### 2. デプロイメントワークフロー

```yaml
name: Deploy to AWS

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .aws/task-definition.json
          service: nature-spots-service
          cluster: nature-spots-cluster
```

### 3. セキュリティスキャン

```yaml
name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0' # 毎週日曜日に実行
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
```

## 移行手順

1. 既存の CircleCI ワークフローの分析
2. GitHub Actions ワークフローの作成と検証
3. 環境変数とシークレットの移行
4. 段階的な移行とテスト
5. モニタリングとパフォーマンス最適化

## セキュリティ考慮事項

- シークレット管理の強化
- OIDC 認証の導入
- 最小権限原則の適用
- 依存関係のセキュリティスキャン

## 期待される効果

- CI/CD パイプラインの高速化
- GitHub 統合による開発フローの改善
- セキュリティの強化
- 運用コストの削減

## タイムライン

1. 設計と計画（1 週間）
2. ワークフロー実装（2 週間）
3. テストと検証（1 週間）
4. 本番環境への移行（1 週間）
5. モニタリングと最適化（1 週間）
